# https://packaging.python.org/en/latest/guides/writing-pyproject-toml/

[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[project]
name = "caissa"
version = "0.1.0"
requires-python = ">= 3.13"
authors = [
  {name = "Jimmy Chin"},
]
maintainers = [
  {name = "Jimmy Chin"}
]
description = "Caissa is an intelligent chess platform for playing, analysing, and improving your game."
license = "MIT"
keywords = ["chess", "stockfish", "pgn", "chess-puzzles", "personalized-learning"]
classifiers = [
  "Development Status :: 1 - Planning",
  "Intended Audience :: End Users/Desktop",
  "Topic :: Games/Entertainment :: Board Games",
  "Programming Language :: Python"
]

[project.urls]
Repository = "https://github.com/jimmy-chin1/caissa"
"Bug Tracker" = "https://github.com/jimmy-chin1/caissa/issues"
Changelog = "https://github.com/jimmy-chin1/caissa/blob/main/CHANGELOG.md"

[project.scripts]
caissa = "app.main:main"

[tool.hatch.build.targets.wheel]
packages = ["app"]

[tool.ruff]
line-length = 88
